// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(rfc string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"loader\" id=\"loader\" style=\"display:none;\"></div><div class=\"container\"><!-- HEADER --><div class=\"row\" style=\"margin-top: 30px; margin-bottom: 20px;\"><div class=\"twelve columns\" style=\"display:flex; align-items:center; gap:12px;\"><img src=\"static/img/logo.svg\" width=\"48\" height=\"48\"><div><h4 style=\"margin-bottom:0;\">Análisis de Proveedores</h4><small style=\"color:#777;\">Consulta de riesgo y cumplimiento</small></div></div></div><!-- SEARCH CARD --><div class=\"row\"><div class=\"twelve columns\" style=\"background:#fff; padding:16px; border-radius:8px; box-shadow:0 2px 10px rgba(0,0,0,0.05);\"><label for=\"searchInput\">RFC del proveedor</label><div style=\"display:flex; gap:10px;\"><input type=\"search\" id=\"searchInput\" placeholder=\"Ej: ABC123456T1\" style=\"flex:1;\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(rfc)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/index.templ`, Line: 26, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"> <button type=\"button\" id=\"searchButton\">Buscar</button></div><small style=\"color:#888;\">Ingresa el RFC para generar el análisis de integridad</small></div></div><!-- RESULTS --><div class=\"row\" style=\"margin-top:20px;\"><div id=\"responseBody\" class=\"twelve columns\"></div></div></div><script src=\"static/lib/marked.min.js\"></script><script src=\"static/index/index.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
