// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(rfc string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"loader-overlay\" id=\"loader\" style=\"background: rgba(15, 23, 42, 0.85); backdrop-filter: blur(4px); position: fixed; inset: 0; z-index: 9999; display: none; align-items: center; justify-content: center;\"><div class=\"loader\" style=\"border: 4px solid #1e293b; border-top: 4px solid #2563eb; border-radius: 50%; width: 40px; height: 40px; animation: spin 1s linear infinite;\"></div></div><div class=\"app-container\"><header style=\"padding: 40px 0 24px 0; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #1e293b; margin-bottom: 32px;\"><div style=\"display: flex; align-items: center; gap: 16px;\"><div style=\"background: linear-gradient(135deg, #1e293b, #334155); padding: 10px; border-radius: 10px; border: 1px solid #475569; display: flex;\"><img src=\"/static/img/logo.png\" width=\"40\" height=\"40\" style=\"filter: brightness(0) invert(1);\"></div><div><h2 style=\"margin: 0; color: #f8fafc; font-size: 24px; font-weight: 700;\">Análisis de Proveedores</h2><p style=\"margin: 4px 0 0 0; color: #94a3b8; font-size: 14px;\">Consulta de riesgo, cumplimiento gubernamental e integridad documental</p></div></div></header><div style=\"background: #1e293b; border-radius: 12px; padding: 24px; border: 1px solid #334155; margin-bottom: 32px;\"><label for=\"searchInput\" style=\"color: #cbd5e1; font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 8px;\">Identificación Fiscal del Proveedor (RFC)</label><div style=\"display: flex; gap: 16px;\"><input type=\"search\" id=\"searchInput\" placeholder=\"Ej: ABC123456T1 o Razón Social...\" style=\"flex: 1; padding: 14px 16px; background: #0f172a; border: 1px solid #475569; color: #f8fafc; border-radius: 8px; font-size: 16px; font-family: monospace; outline: none; margin: 0;\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(rfc)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/index.templ`, Line: 29, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"> <button type=\"button\" id=\"searchButton\" style=\"background: #2563eb; color: white; border: none; padding: 0 32px; border-radius: 8px; font-weight: 600; font-size: 15px; cursor: pointer; transition: all 0.2s; display: flex; align-items: center; gap: 8px;\" onmouseover=\"this.style.background='#1d4ed8'\" onmouseout=\"this.style.background='#2563eb'\">🔍 Ejecutar Análisis</button></div></div><div id=\"responseBody\"></div></div><script src=\"/static/lib/marked.min.js\"></script><script src=\"/static/index/index.js\"></script><style>@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
