// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(rfc string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"loader-overlay\" id=\"loader\"><div class=\"loader\"></div></div><div class=\"container\"><header class=\"row\" style=\"margin-top: 40px; margin-bottom: 30px;\"><div class=\"twelve columns\" style=\"display:flex; align-items:center; gap:16px;\"><img src=\"/static/img/logo.png\" width=\"56\" height=\"56\" style=\"filter: brightness(0) invert(1);\"><div><h3 style=\"margin-bottom:0; color: #f8fafc;\">Análisis de Proveedores</h3><span style=\"color:#94a3b8; font-size: 14px;\">Consulta de riesgo y cumplimiento gubernamental</span></div></div></header><div class=\"row\"><div class=\"twelve columns content-card\"><label for=\"searchInput\" style=\"color: #cbd5e1;\">RFC del proveedor</label><div style=\"display:flex; gap:12px; margin-top: 8px;\"><input type=\"search\" id=\"searchInput\" placeholder=\"Ej: ABC123456T1\" style=\"flex:1; margin-bottom: 0;\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(rfc)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/index.templ`, Line: 26, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"> <button type=\"button\" id=\"searchButton\">Buscar</button></div><p style=\"color:#64748b; font-size: 12px; margin-top: 12px; margin-bottom: 0;\"><i class=\"icon-info\"></i> Ingresa el RFC para generar el análisis de integridad documental.</p></div></div><div class=\"row\" style=\"margin-top:30px;\"><div id=\"responseBody\" class=\"twelve columns\"></div></div></div><script src=\"/static/lib/marked.min.js\"></script><script src=\"/static/index/index.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
