// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func disclaimer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"disclaimer-container\"><button type=\"button\" class=\"disclaimer-trigger\" onclick=\"document.getElementById('disclaimer-content').classList.toggle('is-visible')\">⚖️ Ver Aviso Legal y Deslinde de Responsabilidad</button><div id=\"disclaimer-content\" class=\"disclaimer-text\"><p><strong>Aviso:</strong> Este reporte fue generado mediante una herramienta digital de apoyo que recopila y organiza información pública, institucional y documental relacionada con proveedores del Gobierno del Estado de Tamaulipas. Su contenido tiene carácter informativo y preventivo, por lo que no constituye una resolución administrativa, dictamen jurídico o determinación definitiva.</p><p>Los hallazgos y clasificaciones de riesgo deberán ser verificados por las áreas competentes antes de tomar cualquier decisión contractual. La herramienta no sustituye la revisión oficial correspondiente.</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Layout(title string, content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!doctype html><html lang=\"es\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout.templ`, Line: 29, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</title><link rel=\"stylesheet\" href=\"/static/css/normalice.css\"><link rel=\"stylesheet\" href=\"/static/css/skeleton.css\"><link rel=\"stylesheet\" href=\"/static/css/overrides.css\"><style>\n\t\t\t\tbody { background-color: #0f172a; color: #f8fafc; font-family: system-ui, -apple-system, sans-serif; margin: 0; padding: 0; }\n\t\t\t\t.app-container { max-width: 1440px; margin: 0 auto; padding: 0 24px; }\n\t\t\t\t.app-footer { margin-top: 60px; padding: 24px 0; border-top: 1px solid #1e293b; color: #64748b; font-size: 13px; }\n\t\t\t\t.disclaimer-container { margin-top: 16px; }\n\t\t\t\t.disclaimer-trigger {\n\t\t\t\t\tbackground: none; border: none; color: #94a3b8;\n\t\t\t\t\ttext-decoration: underline; cursor: pointer; font-size: 13px; padding: 0;\n\t\t\t\t}\n\t\t\t\t.disclaimer-trigger:hover { color: #f8fafc; }\n\t\t\t\t.disclaimer-text {\n\t\t\t\t\tdisplay: none; font-size: 12px; color: #94a3b8;\n\t\t\t\t\ttext-align: justify; margin-top: 12px; line-height: 1.5;\n\t\t\t\t\tbackground: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;\n\t\t\t\t}\n\t\t\t\t.disclaimer-text.is-visible { display: block; }\n\t\t\t</style></head><body><main class=\"app-main\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main><footer class=\"app-footer\"><div class=\"app-container\"><span>© 2026 Sistema Interno de Análisis de Integridad Gubernamental — Estado de Tamaulipas</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = disclaimer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
